### ISSUE TITLE
Database selection

### ISSUE THREAD

**Issue by razor06** [c-ruttkies/MetFragR#12]
Hi,

I wonder how I can choose an external sdf as database option, instead of using Kegg or PubChem. Is this feature coming up, or is it already in the R script but I did not find it? 

Daniel

**Comment by lucanard** [comment]
You can already do this, using the function "score.molecules.from.sdf" that is already in the package. 
You can supply whatever sdf you want, I guess.

**Comment by c-ruttkies** [comment]
Hi,

sorry for the delay. The package has been redesigned and upgraded to version 2.0. The method score.molecules.from.sdf is still be available and can be used for this purpose as lucanard mentioned.

Best regards,
Christoph

**Comment by MiriMet** [comment]
Hi,

I am trying to use the method "score.molecules.from.sdf" following your example:
file<-"sdf/MetFrag_Candidates.sdf"
sdf <- system.file(file, package = "metfRag")
molecules <- load.molecules(sdf)

And I get this error:
Error in as.character.default(X[[i]], ...) : 
  no method for coercing this S4 class to a vector


Miriam

**Comment by MiriMet** [comment]
Hi Christoph,

Thank you for you kind answer. Finally I decided to use metfrag with
command line since R reported another error related to the memory space. I
could use metfrag using PubChem database, but when I try to use the
downloaded structures from HMDB in SDF format I get an error (I attached in
this email).

Would you know how I can resolve it?

Thank you very much in advance,

Best regards,

Miriam

2016-09-10 10:49 GMT+02:00 c-ruttkies <notifications@github.com>:

**Comment by c-ruttkies** [comment]
Hi Miriam,

I didn't get an email with the attached error. Could you please send your example directly to cruttkie@ipb-halle.de ?

Thanks in advance.

Best regards,
Christoph
